#!/usr/bin/env bash

# simple script to interact with discord using a webhook
# simple and rich post sending to a single discord channel
# (channel set in 'webhooks' in server settings)
#
# author: Little Tinker/Thom Cuddihy (https://github.com/thomcuddihy)
# MIT License 2017

HELP="
arguments:
    T: Webhook token
    G: Guild code
    t: text to post (appears above rich message if used)
    r: rich message
    c: colour of rich message (as ascii integer or: good|warning|danger) (optional)
    H: rich text header (title) (optional)
    l: rich text header url link (optional)
    a: avatar icon url (optional)
    u: username to post as (optional)
    h: help
notes:
    Guild code and webhook token can be extracted from the webhook url:
        https://discordapp.com/api/webhooks/{{ guild code }}/{{ token }}
    One or both of '-t' and '-r' are required, all else optional
    Webhook token and guild code can be omitted and set in environment instead:
        export DISCORD_GUILD=...
        export DISCORD_TOKEN=...
    You can mention users/roles in messages using their id codes:
        Enter '\@Something' in discord chat to get their id code
        Then use in messages as '<@1234567890>'
    '-c' takes either an ascii rgb integer or defined words
        Ascii rgb integers are weird. blame discord for not using hex strings
        Use this to convert: https://www.shodor.org/stella2java/rgbint.html
examples:
    ./postdiscord -t 'boop' -r 'I'm a rich embed!' -c 'good' -H 'test script' -u 'Feldb0t'
    ./postdiscord -t 'boop' -r 'I'm a rich embed with a custom colour!' -c '16738740' -H 'test script'
    ./postdiscord -t 'I'm a plain message' -u 'AppleBot'
    ./postdiscord -t 'Hi <@1234567890>' -r 'boop' -c 'warning' -H 'Mention example' -u 'Sweetie Bot'
"

## Check if null arguments
if [ $# -eq 0 ]; then
    echo "$HELP"
    exit
fi

#Set vars
URL_BASE="https://discordapp.com/api/webhooks"
COLOUR="8421504"

## Load var from environment:
GUILD=$DISCORD_GUILD
TOKEN=$DISCORD_TOKEN

## Setup vars from arguments
while getopts 'T:G:t:r:c:H:l:a:u:h' opt; do
    case $opt in
        T)  TOKEN="$OPTARG"         ;;
        G)  GUILD="$OPTARG"         ;;
        t)  TEXT="$OPTARG"          ;;
        r)  RICH="$OPTARG"          ;;
        c)  COLOUR="$OPTARG"        ;;
        H)  TITLE="$OPTARG"         ;;
        l)  TITLE_URL="$OPTARG"     ;;
        a)  AUTHOR_ICON="$OPTARG"   ;;
        u)  USERNAME="$OPTARG"      ;;
        h)  echo "$HELP"
            exit                    ;;
        *)  echo "$HELP" >&2
            exit 1                  ;;
    esac
done

## colour strings...
if [ ${COLOUR} = "good" ]; then COLOUR="65280"; fi
if [ ${COLOUR} = "warning" ]; then COLOUR="255"; fi
if [ ${COLOUR} = "danger" ]; then COLOUR="16711680"; fi
if [ ${COLOUR} = "pinkie" ]; then COLOUR="16738740"; fi

## post url
POST_URL=${URL_BASE}/${GUILD}/${TOKEN}

## Rich attachment post
if [[ -n ${RICH} ]]; then
    curl -X POST ${POST_URL} \
    --header "Content-Type: application/json" -d @- << EOF
{"content":"${TEXT}",
"username":"${USERNAME}",
"avatar_url":"${AUTHOR_ICON}",
"embeds":[{
"title": "${TITLE}",
"description": "${RICH}",
"color": "${COLOUR}",
"url": "${TITLE_URL}"
}]}
EOF

## Normal post
else
    curl -X POST ${POST_URL} \
    --header "Content-Type: application/json" -d @- << EOF
{"content":"${TEXT}",
"username":"${USERNAME}",
"avatar_url":"${AUTHOR_ICON}"
}
EOF

fi